{% set name = "sluarch" %}
{% set version = "2024.5.16" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3ff2f92bf65450701650efa5920f34b4b37f940b1ebf36b7f9dac80a1b08ba25

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - poetry-core >=1.0.0
    - pip
    - python {{ python_min }}
  run:
    - python {{ python_min }}
    - outdated
    - mne>=1.6.0
    - numpy>=1.25.0
    - pandas>=2.2.0
    - scipy>=1.12.0


test:
  imports:
    - sluarch
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/sluarch/
  summary: 'SlµArch (Sleep MicroArchitecture): open-source Python package to analyse sleep microarchitecture.'
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://github.com/sjg2203/SluArch/blob/main/README.md
  dev_url: https://github.com/sjg2203/SluArch

extra:
  recipe-maintainers:
    - sjg2203
